### ISSUE TITLE
大佬考虑出个Vue3的版本吗？

### ISSUE THREAD

**Issue by jackyyyy-dev** [font-size/vue-quill-xiumi-135#1]
感谢有这个项目，用着爽

目前新项目以vue3为主   尝试按目前的接入方式添加，奈何Quill配置太多    没接成功 :-(

能弹框显示秀米和135的编辑器   但是点击完成后不能触发messge回弹数据

> 所以会考虑出v3的版本吗？

**Comment by font-size** [comment]
暂时不考虑。vue3更新很快，秀米更新也很快，结合起来维护难度比较大
